### ISSUE TITLE
Wrong dist-tags in meta

### ISSUE THREAD

**Issue by sipayRT** [iarna/aproba#8]
Hi

There are some wrong dist-tags in [meta](https://skimdb.npmjs.com/registry/aproba) that can't be parsed by `bson` parser (for example, `abc\u00123`). Can you remove such tags, pls? See npm doc how to do it correctly - https://docs.npmjs.com/cli/dist-tag

tnx!

**Comment by sipayRT** [comment]
@iarna ping

**Comment by rostik404** [comment]
@iarna ping, this issue is very important for us

**Comment by iarna** [comment]
Ah yeah, I created those tags when I discovered the dist-tag end point had no validation, and I was testing the bounds of its limits. I'm not opposed to removing them. IIRC, I can't install them, but I might be able to remove them (I don't recall if I tried).

That being said, that page is valid JSON which is the only guarantee that we make. If you're trying to store JSON data in a format that doesn't support valid JSON you're gonna have a bad day.

If I were you though, I would make sure you can handle emoji as we _probably_ will make those officially supported at some point.

**Comment by iarna** [comment]
Ok, so the conclusion is that I was able to remove them by hand crafting `curl` calls. 😆

```console
$ npm dist-tag ls aproba
latest: 1.2.0
😄: 1.1.1
```
